### PR TITLE
WIP: better multiline command support, multiple root_dirs

### PR DESCRIPTION
**Pull request by noelbk**
Hi and thanks for MOcov!  We'll be using it to unit test our octave project.

I ran into two issues:

1, we have a lot of multiline commands that the 'file' mode can't parse correctly so it injects syntax errors.  I fixed that in a pretty simple way by putting the `mocov_line_covered()` call after lines ending in ';'.  That worked quite well with our code.

2. We have a lot of code directories, so I made MOcov accept multiple root_dirs

Are these changes OK with you?  I still have to update the docs and unit tests.  Do you know what this unit test error means?

```
failure: `    aProp;` line is wrongly classified as executable
  assert:94 (/usr/share/octave/4.0.0/m/testfun/assert.m)
  test_MOcovMFile_recognizes_classdef_syntax>test_properties_line_not_executable:119 (/home/noel/projects/phil/prolira/algoalpha/MOcov/tests/test_MOcovMFile_recognizes_classdef_syntax.m)

failure: Problems when running the decoated file: /tmp/AClassNNJVCUMQJOJWGIICNHHM.m - please check for syntax errors.
  assert:94 (/usr/share/octave/4.0.0/m/testfun/assert.m)
  test_MOcovMFile_recognizes_classdef_syntax>test_generate_valid_file:155 (/home/noel/projects/phil/prolira/algoalpha/MOcov/tests/test_MOcovMFile_recognizes_classdef_syntax.m)

```

Thanks again for making this open source!   Nice coding style too.

### CODE REVIEW

**Comment by nno** [comment]
Hello @noelbk,

thanks for the Pull Request, much appreciated. I would definitely support the changes that you propose, under the condition that they are properly documented and tested, and that the test suite passes. So for now I will consider your PR as work in progress, and not yet as ready-to-merge-into-master.

The first error is indicating that with your changes the line ``aProp;``, when inside a class definition
```
classdef foo < handle
  properties
    aProp;
  end
[...]
```
is considered by the parser as executable, and thus should have a call to ``mocov_line_covered`` added. It should not be considered executable; it seems your new code does not take such classdef cases correctly into account. 

The second error is a bit harder to understand because the error is caught in a try-catch body. The error indicates that evaluating a string with Matlab code raised an exception. To debug this you start with temporarily removing the try-catch statement in ``test_generate_valid_file``. 

Please let me know if you run into issues, or when you have updated the code with documentation and tests. 

Best,
Nick

**Comment by noelbk** [comment]
Thanks @nno !  I'm wrapping up another project, but hope to get back to this next week.  Wow, you learn something every day: classdef?  Who knew!  OK, I'll fix up the unit tests, probably by restoring your is_in_classdef parse checks.

**Comment by nno** [comment]
@noelbk, do you have any plans to update your PR?

**Comment by noelbk** [comment]
Hi @nno.  I keep meaning to, but work gets in the way, and we no longer need the change.  It's hung up on unit tests for classes.  I don't have any immediate plans to implement those.

**Pull request closed without merging**
